In [1]:
!pip install tweepy
!pip install configparser
!pip install pandas
!pip install tweepy[async]
!pip install git+https://github.com/tweepy/tweepy.git
!pip install textblob
import tweepy
import pandas as pd
import numpy as np
import requests
import os
import re
import csv

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: tweepy in /usr/local/lib/python3.7/dist-packages (3.10.0)
Requirement already satisfied: requests[socks]>=2.11.1 in /usr/local/lib/python3.7/dist-packages (from tweepy) (2.23.0)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.7/dist-packages (from tweepy) (1.15.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.7/dist-packages (from tweepy) (1.3.1)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from requests-oauthlib>=0.7.0->tweepy) (3.2.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests[socks]>=2.11.1->tweepy) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests[socks]>=2.11.1->tweepy) (2022.5.18.1)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests[socks]>=2.11.1->tweepy) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests[socks]>=2.11.1->tweepy) (3.0.4)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.7/dist-packages (from requests[socks]>=2.11.1->tweepy) (1.7.1)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting configparser
  Downloading configparser-5.2.0-py3-none-any.whl (19 kB)
Installing collected packages: configparser
Successfully installed configparser-5.2.0
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (1.3.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2022.1)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (1.21.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: tweepy[async] in /usr/local/lib/python3.7/dist-packages (3.10.0)
WARNING: tweepy 3.10.0 does not provide the extra 'async'
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.7/dist-packages (from tweepy[async]) (1.3.1)
Requirement already satisfied: requests[socks]>=2.11.1 in /usr/local/lib/python3.7/dist-packages (from tweepy[async]) (2.23.0)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.7/dist-packages (from tweepy[async]) (1.15.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from requests-oauthlib>=0.7.0->tweepy[async]) (3.2.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests[socks]>=2.11.1->tweepy[async]) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests[socks]>=2.11.1->tweepy[async]) (2022.5.18.1)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests[socks]>=2.11.1->tweepy[async]) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests[socks]>=2.11.1->tweepy[async]) (2.10)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.7/dist-packages (from requests[socks]>=2.11.1->tweepy[async]) (1.7.1)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting git+https://github.com/tweepy/tweepy.git
  Cloning https://github.com/tweepy/tweepy.git to /tmp/pip-req-build-hikb4iqh
  Running command git clone -q https://github.com/tweepy/tweepy.git /tmp/pip-req-build-hikb4iqh
Requirement already satisfied: oauthlib<4,>=3.2.0 in /usr/local/lib/python3.7/dist-packages (from tweepy==4.10.0) (3.2.0)
Collecting requests<3,>=2.27.0
  Downloading requests-2.28.0-py3-none-any.whl (62 kB)
     |████████████████████████████████| 62 kB 1.7 MB/s
Requirement already satisfied: requests-oauthlib<2,>=1.2.0 in /usr/local/lib/python3.7/dist-packages (from tweepy==4.10.0) (1.3.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests<3,>=2.27.0->tweepy==4.10.0) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests<3,>=2.27.0->tweepy==4.10.0) (2022.5.18.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests<3,>=2.27.0->tweepy==4.10.0) (1.24.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.7/dist-packages (from requests<3,>=2.27.0->tweepy==4.10.0) (2.0.12)
Building wheels for collected packages: tweepy
  Building wheel for tweepy (setup.py) ... done
  Created wheel for tweepy: filename=tweepy-4.10.0-py3-none-any.whl size=94559 sha256=ec234eee0f93554036bf3d7adb431af3f51e6fe3913b7f539da47881c48a54f4
  Stored in directory: /tmp/pip-ephem-wheel-cache-ar06owgu/wheels/b4/a5/5a/5074abdb9f4bd5bd0e22631a63fc41ae2fa71ad83780ea18d1
Successfully built tweepy
Installing collected packages: requests, tweepy
  Attempting uninstall: requests
    Found existing installation: requests 2.23.0
    Uninstalling requests-2.23.0:
      Successfully uninstalled requests-2.23.0
  Attempting uninstall: tweepy
    Found existing installation: tweepy 3.10.0
    Uninstalling tweepy-3.10.0:
      Successfully uninstalled tweepy-3.10.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests~=2.23.0, but you have requests 2.28.0 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
Successfully installed requests-2.28.0 tweepy-4.10.0
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: textblob in /usr/local/lib/python3.7/dist-packages (0.15.3)
Requirement already satisfied: nltk>=3.1 in /usr/local/lib/python3.7/dist-packages (from textblob) (3.2.5)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from nltk>=3.1->textblob) (1.15.0)

In [2]:
!pip install Afinn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting Afinn
  Downloading afinn-0.1.tar.gz (52 kB)
     |████████████████████████████████| 52 kB 1.5 MB/s
Building wheels for collected packages: Afinn
  Building wheel for Afinn (setup.py) ... done
  Created wheel for Afinn: filename=afinn-0.1-py3-none-any.whl size=53447 sha256=328da1d9f5cdad15763d3ce1f78695271d39c99419fc461572ff0f4665efff97
  Stored in directory: /root/.cache/pip/wheels/9d/16/3a/9f0953027434eab5dadf3f33ab3298fa95afa8292fcf7aba75
Successfully built Afinn
Installing collected packages: Afinn
Successfully installed Afinn-0.1

In [3]:
df = pd.read_csv('/content/drive/MyDrive/fyp/fyp2/Bitcoin_tweets_cleaned.csv')
df.replace("", np.nan, inplace=True) # replace empty string with np.nan
df.dropna(subset = ["tweet"], inplace=True) # drop nan values

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (0,3) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [4]:
##afinn lexicon

from afinn import Afinn
af = Afinn()

df.dropna(subset = ["tweet"], inplace=True)

score_df = []

for sentence in df['tweet']:
    score = af.score(sentence)
    #print(f'The sentiment value of the sentence :"{sentence}" is : {score}')
    score_df.append(score)
    #print(score)

df_score = pd.DataFrame(score_df,columns=['score'] )
display(df_score)

         score
0          1.0
1          1.0
2          3.0
3          0.0
4         -1.0
...        ...
3533372    0.0
3533373    0.0
3533374    0.0
3533375    0.0
3533376    0.0

[3533377 rows x 1 columns]

In [6]:
#df = df_clean
display(df_score)
display(df)
df_t = df.copy()
df_t['afinn_score'] = df_score
display(df_t)
#df_score.to_csv('/content/drive/MyDrive/fyp/fyp2/scores/textblob_score.csv')
df_t.to_csv('/content/drive/MyDrive/fyp/fyp2/scores/afinn_score.csv')

         score
0          1.0
1          1.0
2          3.0
3          0.0
4         -1.0
...        ...
3533372    0.0
3533373    0.0
3533374    0.0
3533375    0.0
3533376    0.0

[3533377 rows x 1 columns]

,Unnamed: 0,date,tweet,is_retweet
0,0,2021-02-10 23:59:04,Blue Ridge Bank shares halted by NYSE after bi...,False
1,1,2021-02-10 23:58:48,"😎 Today, that's this Thursday, we will do a ""🎬...",False
2,2,2021-02-10 23:54:48,"Guys evening, I have read this article about B...",False
3,3,2021-02-10 23:54:33,51) Bitcoin FX BTC crypto,False
4,4,2021-02-10 23:54:06,BTC in too big to fail…,False
...,...,...,...,...
3533374,3543848,2022-05-30 00:00:03,1790.98\n\n03 UTC\n03 JST\n &gt; 29430.0 la...,False
3533375,3543849,2022-05-30 00:00:02,"$29,465 \nBitcoin BTC BitcoinPrice Crypto",False
3533376,3543850,2022-05-30 00:00:02,ASTRO BOT ALE$BTCUSDT\n\n2h\n\n LONG(Buy) from...,False
3533377,3543851,2022-05-30 00:00:01,Hiring?\nSign up now \nFREE. NO MIDDLEMEN\nJob...,False
3533378,3543852,2022-05-30 00:00:00,"\n \n $29,482\n +0.02%\n +1.35%\n -0.03%\n ...",False

,Unnamed: 0,date,tweet,is_retweet,afinn_score
0,0,2021-02-10 23:59:04,Blue Ridge Bank shares halted by NYSE after bi...,False,1.0
1,1,2021-02-10 23:58:48,"😎 Today, that's this Thursday, we will do a ""🎬...",False,1.0
2,2,2021-02-10 23:54:48,"Guys evening, I have read this article about B...",False,3.0
3,3,2021-02-10 23:54:33,51) Bitcoin FX BTC crypto,False,0.0
4,4,2021-02-10 23:54:06,BTC in too big to fail…,False,-1.0
...,...,...,...,...,...
3533374,3543848,2022-05-30 00:00:03,1790.98\n\n03 UTC\n03 JST\n &gt; 29430.0 la...,False,0.0
3533375,3543849,2022-05-30 00:00:02,"$29,465 \nBitcoin BTC BitcoinPrice Crypto",False,0.0
3533376,3543850,2022-05-30 00:00:02,ASTRO BOT ALE$BTCUSDT\n\n2h\n\n LONG(Buy) from...,False,0.0
3533377,3543851,2022-05-30 00:00:01,Hiring?\nSign up now \nFREE. NO MIDDLEMEN\nJob...,False,NaN
3533378,3543852,2022-05-30 00:00:00,"\n \n $29,482\n +0.02%\n +1.35%\n -0.03%\n ...",False,NaN

10.0